### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by Edward-Stryfe** [fastcast/fastcast#11]
Is there a reason for the website down? Was it costing too much to keep the server and DNS up? Or was the project not receiving enough help or support.

**Comment by jakefb** [comment]
Hi @Edward-Stryfe I apologise, I forgot to top up my balance so the domain could be renewed. I will make sure I keep the website up from now on. Any support would also be appreciated :+1:

**Comment by Edward-Stryfe** [comment]
Gotcha it's cool I wasn't sure if the project was just abandoned
