### ISSUE TITLE
Why not show player 

### ISSUE THREAD

**Issue by alamcordeiro** [fastcast/fastcast#3]
OS X 10.10.4
Chrome 43/ Firefox 38
10 mbps internet

Accessing http://fastcast.nz/videos/awakening-new-zealand-4k.html not show player

On debug status the tracker is pending for hours
```
Request URL:wss://tracker.webtorrent.io/
Request Method:GET
Status Code:101 Switching Protocols
```

![captura de tela 2015-06-28 as 12 09 58](https://cloud.githubusercontent.com/assets/1471463/8397373/a99f0e0c-1d8e-11e5-9610-02b3ff91e6b2.png)

This issue persist on [Fastcast app] (https://github.com/fastcast/fastcast-app)

**Comment by jakefb** [comment]
Have you tried seeding the video? http://fastcast.nz/seed.html

**Comment by alamcordeiro** [comment]
Yes, seeding the video player is displayed.:smiley: 
Why ?
Not have others seeds ?
[http seed] (http://www.bittorrent.org/beps/bep_0019.html) ?

**Comment by alamcordeiro** [comment]
webtorrent not yet support http seed
https://github.com/feross/webtorrent/issues/67

**Comment by alamcordeiro** [comment]
Hello,
Actually the videos do not have seeds.

My solution has seed files using [webtorrent-hybrid] (https://github.com/feross/webtorrent-hybrid) on my server:

```
var WebTorrent = require('webtorrent-hybrid')
var client = new WebTorrent()
client.seed('awakening-new-zealand-4k.mp4', function (torrent) {
        console.log(torrent.infoHash, torrent.files[0].name);
});

```
Now player is accessible on  http://fastcast.nz/videos/awakening-new-zealand-4k.html

**Comment by jakefb** [comment]
Thanks, I can load the player on http://fastcast.nz/videos/awakening-new-zealand-4k.html without seeding myself. There used to be a bug which prevented seeding from continuing using WebTorrent command line, but I guess this has been fixed. I will add this code to the README.md. Would you be able to test this out on your server to see if you can seed multiple videos?

**Comment by jakefb** [comment]
There isn't any support for HTTP seeding yet unfortunately. I was planning on using that as a long term solution to seeding.

**Comment by alamcordeiro** [comment]
Yes seeding stop works after time :cry: 

My test seed using command line stop after 7931 seconds (~132 minutes)

The last log:
```
seeding: awakening-new-zealand-4k.mp4
info hash: ab3f1350ebe4563a710545d0e33e09a7b7943ecf
speed: 0 B/s
downloaded: 0 B/156.82 MB
uploaded: 56.44 MB
peers: 0/0
hotswaps: 0
time remaining: 5 years remaining
total time: 7931s
queued peers: 0
blocked: 0

**Comment by jakefb** [comment]
Yeah I was having this problem too. You could try opening a new issue in WebTorrent. I think it has something to do with a memory leak. I have tried using [forever](https://github.com/foreverjs/forever) but no luck.

**Comment by alamcordeiro** [comment]
okay, testing with [PM2] (https://github.com/Unitech/pm2) now.

**Comment by jakefb** [comment]
Sweet, let me know how it goes!

**Comment by alamcordeiro** [comment]
Memory usage now is 300MB and upping :D
Our problem is this: 
https://github.com/feross/webtorrent-hybrid/issues/5

**Comment by jakefb** [comment]
Well the inelegant solution could be to restart the process with PM2 each time it reaches a certain amount of memory. I'm interested what amount of memory it takes for the process to crash. [Fastcast App](https://github.com/fastcast/fastcast-app) has web seeding working in Electron, but the code needs some improvemsnt.

**Comment by alamcordeiro** [comment]
13 hours after, node seed app has restarted 2x and is online
... but now use 100% of CPU and not works.

**Comment by jakefb** [comment]
Damn, I'll have a look at other ways we can get around this soon!

**Comment by feross** [comment]
This sucks. I'm sorry about this memory leak. It's caused by the `wrtc` dependency in `webtorrent-hybrid` I think.

**Comment by Ortix92** [comment]
So is there a reason why the player is not showing in any of my browsers? I'm on OSX yosemite

**Comment by jakefb** [comment]
I'm away on holiday, but in the mean while you will have to seed the video yourself in order for the player to show http://fastcast.nz/seed.html. This is because we don't have HTTP seeding setup yet; when I get back I will fix this problem.

**Comment by jakefb** [comment]
@alamcordeiro @Ortix92 This works now and has been resolved [here](https://github.com/fastcast/fastcast/blob/fdfcc53c141333c5f5a46ad08910dd7cb6b2a877/client/stream-torrent.js). The torrent file is now loaded from the server instead of using magnet links and the videos instantly start buffering from the WebSeed!

**Comment by feross** [comment]
@jakefb Nice work -- looks like it's working great!
