### ISSUE TITLE
not play correctly after switching video

### ISSUE THREAD

**Issue by pminmax945** [fastcast/fastcast#8]
first time ,everything works, but after switching video,
video automaticly enter 'playing' state (without pressing playing triangle) 
but waiting circle always showing in playing area, nothing played
download progress can still to 100%

but if pause then play ,seems new video can play correctly

**Comment by jakefb** [comment]
Hi @pminmax945,

Sorry for the late reply. Do you still have this issue? Could you please enter `localStorage.debug = '*'` into the console, reload the page and check if there are any errors in the console log?
